version: "3"
services:
  geth:
    image: ethereum/client-go:latest
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    volumes:
      - ./ethereum/:/root
      - ./ethereum/jwt.hex:/root/jwt.hex
    command:
      - --mainnet
      - --http
      - --http.api
      - "debug,eth,net,web3,txpool,engine"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.api
      - "eth,net,web3,txpool,engine"
      - --ws.addr=0.0.0.0
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/root/jwt.hex
#
  lighthouse:
    image: sigp/lighthouse:latest-unstable
    restart: unless-stopped
    volumes:
      - ./ethereum/lighthouse:/root/.lighthouse
      - ./ethereum/jwt.hex:/root/jwt.hex
    links:
      - geth
    command:
      - lighthouse
      - bn
      # uncomment line below to purge lighthouse and start from checkpoint URL.
      #- --purge-db
      - --checkpoint-sync-url=https://mainnet-checkpoint-sync.stakely.io
      - --eth1-endpoints=http://[Insert IP, docker host does not resolve correctly]:8545
      - --execution-endpoints=http://[Insert IP, docker host does not resolve correctly]:8551
      - --network=mainnet
      - --jwt-secrets=/root/jwt.hex